version: '3'
services:
  pgadmin:
    container_name: pgadmin
    # image: dpage/pgadmin4
    build:
      context: './compose/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DOMAIN_NAME: ${DOMAIN_NAME}
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 30
      CONF_DIR: "/pgadmin4"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    stop_signal: SIGINT
    networks:
      - database
    # logging:
    #   driver: none
    volumes: [ "pgadmin:/var/lib/pgadmin" ]
      # - ./servers.json:/pgadmin4/to_subst.json
      # - ./compose/pgadmin4/pgpass.sh:/pgpass.sh

  # Add mailhog webui available
  mailhog:
    ports:
      - ${MAILHOG_PORT:-8025}:8025

volumes:
  pgadmin:
