version: '3'
services:
  api:
    environment:
      - NODE_ENV=PROD
      - DEBUG=0
  front:
    environment:
      - NODE_ENV=PROD
      - DEBUG=0
  api:
    environment:
      - NODE_ENV=PROD
      - DEBUG=0
